---

- name: Configure a practice image
  hosts: "{{ host | default('lab') }}"
  become: yes

  vars:
    - role: planetexpress

  tasks:
    - name: Include role {{ role }}
      include_role:
        name: "{{ role }}"
