---
- name: Install Jinja
  apt:
    name: python3-jinja2

- name: Copy ScoringEngine Directory
  copy:
    src: opt/ScoringEngine
    dest: /opt/
  
- name: Copy score command
  copy:
    src: score
    dest: /usr/bin
    mode: "0755"

- name: Copy Updater for On The Fly Updates
  copy:
    src: update-engine
    dest: /usr/bin
    mode: "0755"

- name: Ensure competitor Desktop directory works
  file:
    path: /home/{{ competitor }}/Desktop
    state: directory
    owner: "{{ competitor }}"
    group: "{{ competitor }}"

- name: Copy README file
  copy:
    src: README.txt
    dest: /home/{{ competitor }}/Desktop
    owner: "{{ competitor }}"
    group: "{{ competitor }}"

- name: Copy Forensics Questions
  copy:
    src: "{{ item }}"
    dest: /home/{{ competitor }}/Desktop
    owner: "{{ competitor }}"
    group: "{{ competitor }}"
  loop:
    - Forensics Question 1.txt

- name: Copy Link to Scoring Report
  file:
    path: /home/{{ competitor }}/Desktop/ScoringReport.desktop
    src: /opt/ScoringEngine/ScoringReport.desktop
    state: link
    force: yes
    owner: "{{ competitor }}"
    group: "{{ competitor }}"

- name: Set permissions on Scoring Report
  file:
    path: /opt/ScoringEngine/ScoringReport.desktop
    mode: +x

- name: Copy Scoring service files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - pe-score.service
    - pe-score.timer

- name: Enable the scoring service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - pe-score.service
    - pe-score.timer

