---
# tasks file for planetexpress
# Setup System
- include_role:
    name: firefox
- name: Install software
  apt:
    name: openssh-server
- name: Enable Services
  service:
    name: ssh
    enabled: yes

- import_tasks: create_users.yml
- import_tasks: install_hacking_tools.yml
- import_tasks: misconfigure_services.yml
- import_tasks: create_scoring_engine.yml