---
# tasks file for planetexpress
# Setup System
- include_role:
    name: firefox

- name: Install software
  apt:
    name: openssh-server
- name: Enable Services
  service:
    name: ssh
    enabled: yes

- name: copy background.png
  copy:
    src: background.png
    dest: /usr/share/backgrounds

- name: Set default dconf configuration
  include_role:
    name: dconf

- name: Don't show first start thing
  lineinfile:
    path: /home/bender/.config/gnome-initial-setup
    line: yes
    create: yes

- import_tasks: create_users.yml
- import_tasks: install_hacking_tools.yml
- import_tasks: misconfigure_services.yml
- import_tasks: create_scoring_engine.yml