---
- name: Create directory
  file:
    path: /usr/local/share/ca-certificates/extra
    state: directory

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: /usr/local/share/ca-certificates/extra
  loop:
    - blocksi.crt
    - ckroot.crt
  notify:
    - update certificates